## dirs
data_dir: "/home/pervinco/Datasets/BKAI_IGH_NeoPolyp"
# data_dir: "/home/pervinco/Datasets/BKAI_FAKE"
save_dir: "./runs"
train: "train"
valid: "valid"
test: "test"
weight_dir: ""

## hyp-params
num_classes: 3
epochs: 500
img_size: 256
batch_size: 16
class_weights: [0.00624089, 0.86719283, 0.12656628]
focal_alpha: 0.25
focal_gamma: 5
l2_lambd: 0.09

red_size: 4
green_size: 8
rng_size: 4

initial_lr: 0.0001 ## 1e-4
last_lr: 0.000001 ## 1e-6
decay_steps: 1000
momentum: 0.9
save_weights_only: True

## augmentation
augment: True
spatial_alpha: 0.45 ## 0.45
mixup_alpha: 0.7

## callbacks
max_lr: 0.0001
min_lr: 0.000001
patience: 50
factor: 0.1
num_pred_samples: 5
early_stopping_patience: 50
